version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["npm", "start", "--prefix", "backend"]
    ports:
      - "4000:4000"
    environment:
      - MICROSERVICE_HOST=server
      - MICROSERVICE_PORT=50051
    volumes:
      - .:/app
  server:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    command: ["npm", "run", "server", "--prefix", "nodejs"]
    environment:
      - SERVER_PORT=50051
  nodejs:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    command: ["npm", "run", "client", "--prefix", "nodejs"]
    environment:
      - SERVER_HOST=grpc.service.equipe.ninja
      - SERVER_PORT=80
  client:
    image: therealplato/grpcc-container:latest
    volumes:
      - .:/app
