version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["npm", "start", "--prefix", "backend"]
    ports:
      - "4000:4000"
    environment:
      - MICROSERVICE_HOST=microservice1
      - MICROSERVICE_PORT=50051
    volumes:
      - .:/app
  microservice1:
    build:
      context: .
      dockerfile: microservice1/Dockerfile
    command: ["npm", "run", "server", "--prefix", "microservice1"]
    environment:
      - MICROSERVICE_PORT=50051
      - MY_NAME=jeanpsv
  nodejs-client:
    build:
      context: .
      dockerfile: microservice1/Dockerfile
    command: ["npm", "run", "client", "--prefix", "microservice1"]
    environment:
      - MICROSERVICE_HOST=microservice1
      - MICROSERVICE_PORT=50051
  client:
    image: therealplato/grpcc-container:latest
    volumes:
      - .:/app
