version: '3'

services:
  server:
    build: .
    command: ["ruby", "src/server.rb"]
    environment:
      - MY_NAME=Vader
      - SERVER_PORT=50051
  client:
    build: .
    command: ["ruby", "src/client.rb"]
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50051
