apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  namespace: apps
spec:
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: app
          image: jeanpsv/gke-grpc-example:backend
          imagePullPolicy: Always
          command: ["npm", "start", "--prefix", "backend"]
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: GREETER_HOST
              value: "greeter.service.my.domain"
            - name: GREETER_PORT
              value: "80"
