apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "backend.service.my.domain"
      http:
        paths:
          - path: /
            backend:
              serviceName: backend
              servicePort: http
