# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "greeter.Person" do
    optional :name, :string, 1
  end
  add_message "greeter.Greeting" do
    optional :message, :string, 1
  end
end

module Greeter
  Person = Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.Person").msgclass
  Greeting = Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.Greeting").msgclass
end
